# cifar with alpha = 0.001
python federated_main.py --model=cnnSimple --dataset=cifar --gpu=0 --dist=4 --num_users 100 --num_Noniid 0 --num_Mislabel 0 --local_ep 2 --epochs 20 --verbose 0 --trainer ka --ka_ep=20 --local_ep_ka 5 --solution_concept pruned_montecarlo_shapley --skip_train --app sampling --alpha 0.001 --sampling clustered_SPACE --sim_type cosine --lr_sampling 0.05
python federated_main.py --model=cnnSimple --dataset=cifar --gpu=0 --dist=4 --num_users 100 --num_Noniid 0 --num_Mislabel 0 --local_ep 2 --epochs 20 --verbose 0 --trainer ka --ka_ep=20 --local_ep_ka 5 --solution_concept pruned_montecarlo_shapley --skip_train --app sampling --alpha 0.001 --sampling clustered_2 --sim_type cosine --lr_sampling 0.05
python federated_main.py --model=cnnSimple --dataset=cifar --gpu=0 --dist=4 --num_users 100 --num_Noniid 0 --num_Mislabel 0 --local_ep 2 --epochs 20 --verbose 0 --trainer ka --ka_ep=20 --local_ep_ka 5 --solution_concept pruned_montecarlo_shapley --skip_train --app sampling --alpha 0.001 --sampling clustered_1 --sim_type any --lr_sampling 0.05
python federated_main.py --model=cnnSimple --dataset=cifar --gpu=0 --dist=4 --num_users 100 --num_Noniid 0 --num_Mislabel 0 --local_ep 2 --epochs 20 --verbose 0 --trainer ka --ka_ep=20 --local_ep_ka 5 --solution_concept pruned_montecarlo_shapley --skip_train --app sampling --alpha 0.001 --sampling random --sim_type any --lr_sampling 0.05

# # cifar with alpha = 10.0
python federated_main.py --model=cnnSimple --dataset=cifar --gpu=0 --dist=4 --num_users 100 --num_Noniid 0 --num_Mislabel 0 --local_ep 2 --epochs 20 --verbose 0 --trainer ka --ka_ep=20 --local_ep_ka 5 --solution_concept pruned_montecarlo_shapley --skip_train --app sampling --alpha 10.0 --sampling clustered_SPACE --sim_type cosine --lr_sampling 0.1
python federated_main.py --model=cnnSimple --dataset=cifar --gpu=0 --dist=4 --num_users 100 --num_Noniid 0 --num_Mislabel 0 --local_ep 2 --epochs 20 --verbose 0 --trainer ka --ka_ep=20 --local_ep_ka 5 --solution_concept pruned_montecarlo_shapley --skip_train --app sampling --alpha 10.0 --sampling clustered_2 --sim_type cosine --lr_sampling 0.1
python federated_main.py --model=cnnSimple --dataset=cifar --gpu=0 --dist=4 --num_users 100 --num_Noniid 0 --num_Mislabel 0 --local_ep 2 --epochs 20 --verbose 0 --trainer ka --ka_ep=20 --local_ep_ka 5 --solution_concept pruned_montecarlo_shapley --skip_train --app sampling --alpha 10.0 --sampling clustered_1 --sim_type any --lr_sampling 0.1
python federated_main.py --model=cnnSimple --dataset=cifar --gpu=0 --dist=4 --num_users 100 --num_Noniid 0 --num_Mislabel 0 --local_ep 2 --epochs 20 --verbose 0 --trainer ka --ka_ep=20 --local_ep_ka 5 --solution_concept pruned_montecarlo_shapley --skip_train --app sampling --alpha 10.0 --sampling random --sim_type any --lr_sampling 0.1